Io multi model
DassHydro-dev/smash pull request #25
Opened 2023-06-08 08:19 UTC by maximejay

Changement principaux : 
- Nouvelles fonctions dans io/hdf5_io.py : fct génériques pour manipuler les hdf5. Passage dict => hdf5, object => hdf5, object => dict, hdf5 => dict, hdf5 => smash_model_object. Possibilité d'ouvri un hdf5 en mode read-only pour pouvoir avoir un acces simultané par plusieurs models. La structure des dictionnaires ou des objet sont conservé lors de l'écriture dans un hdf5. Plusieurs objet ou dictionnaire peuvent être écrit dans un unique hdf5 cote à cote.
- Nouvelle option pour lire la pluie : prcp_yymmdd_access, lecture dans un répertoire yy/mm/dd. Cette option est utile lorsque le model et lancé pas de temps par pas de temps, afin d'éviter de faire le glob à la racine du répertoire. le glob est fait intelligement dans les répertoir yy ou mm ou dd en fonction de la date de départ et de fin de simulation.
- Nouveau mode de régularisation : hard-smothing
- Correction de bug lors de la fabrication de la l-curve

2023-07-01 12:14 UTC, inoelloc requested changes
Voila ma review:
- Formatter les fichiers avec black. 
- Résoudre conflit mineur sur le fichier de la release note

2023-07-01 12:14 UTC, inoelloc commented on smash/io/hdf5_io.py
> +__all__ = ["save_object_to_hdf5", "save_dict_to_hdf5", "save_smash_model_to_hdf5", "load_hdf5_file", "read_object_as_dict"]
Faut que ce soit les memes que dans le fichier \_\_init\_\_.py A priori ca devrait etre ca
```suggestion
__all__ = ["save_smash_model_to_hdf5, load_hdf5_file, generate_smash_object_structure"]
```

2023-07-01 12:14 UTC, inoelloc commented on smash/io/hdf5_io.py
> +        if replace==True:
```suggestion
        if replace:
```

2023-07-01 12:14 UTC, inoelloc commented on smash/io/hdf5_io.py
> +                    f"unconsistant {attr} in {list_attr}. {attr} must be a an instance of dict, list or str"
```suggestion
                    f"inconsistent {attr} in {list_attr}. {attr} must be a an instance of dict, list or str"
```

2023-07-01 12:14 UTC, inoelloc commented on smash/io/hdf5_io.py
> +                    f"Bad type of '{attr}' in '{dict_attr}'. Dict({attr}) must be a instance of dict, list or str"
Juste pour être homogène avec la fonction **dump_object_to_hdf5_from_list_attribute**
```suggestion
                    f"inconsistent '{attr}' in '{dict_attr}'. Dict({attr}) must be a instance of dict, list or str"
```

2023-07-01 12:14 UTC, inoelloc commented on smash/io/hdf5_io.py
> +def read_hdf5_to_model_object(path: str) -> Model:
Du coup ca doit remplacer la fonction save_model ?

2023-07-01 12:14 UTC, inoelloc commented on smash/solver/derived_type/mwd_setup.f90
> +!%      ``prcp_yymmdd_access``     Access with absolute path (YY/MM/dd/)                  (default: .false.)
```suggestion
!%      ``prcp_yyyymmdd_access``     Access with absolute path (YYYY/MM/dd/)                  (default: .false.)
```

2023-07-01 12:14 UTC, inoelloc commented on smash/solver/derived_type/mwd_setup.f90
> +        logical :: prcp_yymmdd_access = .false.
```suggestion
        logical :: prcp_yyyymmdd_access = .false.
```

2023-07-01 12:14 UTC, inoelloc commented on smash/__init__.py
> +from smash.io.hdf5_io import save_smash_model_to_hdf5, load_hdf5_file, generate_smash_object_structure
Faudra juste voir le nouveau qu'on donne a ce fichier

2023-07-03 08:21 UTC, maximejay commented on smash/io/hdf5_io.py
> +def read_hdf5_to_model_object(path: str) -> Model:
Oui c'est la même. Elle est wrappé par load_hdf5_file(hdf5file,as_model=False). QUi renvoie soit un objet model si as_model=True soit un dictionnaire.

2023-07-03 08:23 UTC, maximejay commented on smash/__init__.py
> +from smash.io.hdf5_io import save_smash_model_to_hdf5, load_hdf5_file, generate_smash_object_structure
Oui, et tiens toi bien,  je pense même que je vais utiliser des underscore pour cacher 2-3 fonctions afin de ne pas trop si perdre (j'y arrive :) )

2023-07-03 09:02 UTC, maximejay commented on smash/core/simulation/_standardize.py
>          )
-La raison était que le code plantait si la fonction optimize est lancé sur 0 pas de temps (date_start = date_end) . j'ai rencontré cette erreur qui à bloqué mes simu dans mon script d'assim ou dans ma fonction model.continu(). 
- pouvoir faire une simulation et sortir des débits à une station même si les débits obs sont manquant sur la période demandée.  De pouvoir lancé une optimization sur 0 pas de temps sans que le code plante: juste un warning, un objet model non modifié et un cost= Na.
- Traité un fichier qobs manquant comme une pluie manquante. Donc faire un warning simplement, et le cost = NA
- Ne pas faire un raisevalue error car cela plante le script python intégralement.  
En fait, il faudrait en effet stopper le lancement du calage car ca ne sert à rien en soit. Mais il ne faut pas que ca génère une erreur, car ici ca stoppe le processus python. 
Comme cela ca fonctionne bien, mais si il n'y a pas d'obs et que l'utilisateur lance un calage sur une longue période... alors il faudrais qd même stopper...

2023-07-03 09:03 UTC, maximejay commented on smash/io/hdf5_io.py
Je vais réfléchir à cela !

2023-07-03 09:10 UTC, maximejay commented on smash/io/hdf5_io.py
> +    from smash.core.model import Model
OK :)

2023-07-05 11:36 UTC, maximejay commented on smash/io/hdf5_io.py
J'ai splité le fichoier en 3 morceau : 
- les fonctions sur l'objet smash.Model sont dans io/hdf5_io.py
- les fonctions générics pour manipuler les hdf5 sont dans tools/hdf5_handler.py
- les fonctions pour manipuler les objet python sont dans  tools/object_handler.py
-

2023-07-05 11:38 UTC, maximejay commented on smash/core/_read_input_data.py
> +def _list_prcp_file(setup):
A terme oui, mais la j'ai pas le temps. Pour l'instant on ne lit que de l'etp journalière ?

2023-07-05 11:40 UTC, maximejay commented
Voila mes corrections et changements :)
- Il semble qu'il y ai un problème sur les tests. Les tests pour les signature plantes. Je me demande si ce n'est pas du au commit de Truyen. Pourtant j'avais fait un merge sur ma branche et il me semble que j'avais regénéré la baseline. Peux tu vérifier cela ?

2023-07-05 15:17 UTC, nghi-truyen commented
Salut Max,
On avait eu des impacts majeurs de la précision de machine (conversion les valeurs de Python-Fortran) dans les calculs de sensible de signatures pour les tests. A priori, les sensibles seront enlevé dans la version 1.0.0. Donc je vais supprimer ce test pour faire passer ton pipeline.

2023-07-05 17:19 UTC, nghi-truyen commented
Salut Max,
En effet, il a avait des changements mineurs sur les calculs des signatures dans maintenance/0.5.x. 
J'ai vu ton commit pour merger maintenance/0.5.x à ta branche. En fait, j'ai appris que quand on fait un merge en local alors ils vont pas être mettre à jour les fichiers hdf5, c'est pour ça il bloque ton pipeline. Je viens de faire un commit qui regénère le baseline. Normalement, tout doit être bon ;)

2023-07-06 07:39 UTC, inoelloc commented
Thanks @nghi-truyen

2023-07-07 08:15 UTC, maximejay commented
Salut,
J'ai changer la modif que j'avais faite à propos de l'erreur générée si pas de débits obs dans optimize(). Pour syntétiser :
1 - c'était un raise valueError()
2- j'avais changer en Warning()
3- j'ai remis en raise valueError()  comme avant
A nous de tester dans nos script avec un bloc try/except les erreur renvoyé par Smash.
Merci 
Est-ce que l'on est bon ?
A++

2023-07-09 14:59 UTC, inoelloc commented
J'imagine qu'on est bon. Je n'ai pas spécialement de temps pour refaire un tour complet de review. Je merge et on passe en 0.5.0 demain

2023-07-09 14:59 UTC, inoelloc approved these changes

2023-07-09 14:59 UTC, merged