* ENC: Add loieau model structure
DassHydro-dev/smash pull request #83
Opened 2023-09-14 08:34 UTC by ThomasdeFournas

- Ajout de la structure loieau (loieau-lr)
- Ajout des 3 nouveaux  paramètres de loieau : ca,kb,cc
- Ajout test structure loieau

2023-09-14 08:53 UTC, nghi-truyen commented on smash/_constant.py
> +            PY_OPTIMIZER, len(PY_OPTIMIZER) * [{"epochs": 200, "early_stopping": False}]
Hum, je remettrais early_stopping est Numerique ici pour la cohérence avec standardize et la doc. Elle prends maintenant un nombre au lieu de booléan. Donc même que les tests passent, default_optimize_options va renvoyer une valeur n'est pas correcte...

2023-09-14 10:23 UTC, inoelloc commented on smash/_constant.py
> +            PY_OPTIMIZER, len(PY_OPTIMIZER) * [{"epochs": 200, "early_stopping": False}]
Il y a un souci de manipulation git du coup on a copié des fichiers. On corrige ca ! Thanks

2023-09-14 12:33 UTC, inoelloc requested changes
Quelques petits changement. N'applique pas directement depuis github, il faut que tu régéneres l'adjoint avec make tap

2023-09-14 12:33 UTC, inoelloc commented on smash/_constant.py
> +    "cc",
```suggestion
    "cc",
    "kb",
```

2023-09-14 12:33 UTC, inoelloc commented on smash/tests/test_constant.py
> +        "cc",
```suggestion
        "cc",
        "kb",
```

2023-09-14 14:31 UTC, inoelloc commented on smash/fcore/forward/md_forward_structure.f90
> +!~             !$OMP& private(i, row, col, ei, pn, en, pr, perc, l, prr, prd, qr, qd)
```suggestion
!~             !$OMP& private(i, row, col, ei, pn, en, pr, perc, prr, prd, qr, qd)
```

2023-09-15 08:21 UTC, inoelloc approved these changes

2023-09-15 08:38 UTC, merged